### ISSUE TITLE
Shiny does not appear to work with Alpine Linux

### ISSUE THREAD

**Issue by hahnemann** [rocker-org/shiny#26]
I am running the latest version of docker using Alpine Linux 3.6 and I can pull the shiny docker file. 

However, when I try to run Shiny via `docker run --rm -p 3838:3838 rocker/shiny` the process does not run. I can verify this via `docker ps` and by pointing my browser to my `ip_addr:3838`. 

I also tried adding Shiny to the rocker/rstudio docker file via `docker run -d -p 3838:3838 -p 8787:8787 -e ADD=shiny rocker/rstudio` and in this case I can access RStudio at port 8787 but I still don't see the Shiny server at port 3838.

**Comment by eddelbuettel** [comment]
If it breaks you get to keep the pieces.  I don't think RStudio claims Alpine is supported.

**Comment by cboettig** [comment]
You're running Alpine as your desktop (server?) distro?  Don't see why that should create a problem; working fine on Ubuntu & Centos machines I've tested. Did you install docker with the `get.docker.com` recipe or native Alpine repo?  If you're running this from a remote server, you've verified that 3838 port isn't firewalled?  

What do you see in the container logs when you run `docker run --rm -p 3838:3838 rocker/shiny`? (should just be printed to console since that command omits the daemon mode).

**Comment by hahnemann** [comment]
I'm pushing this a bit due to hardware limitations, so I installed the [virtual version of Alpine](https://alpinelinux.org/downloads/) running on top of VMware Fusion in OS X El Capitan. I then installed docker using [this wiki](https://wiki.alpinelinux.org/wiki/Docker). There are no firewalled ports, as far as I can tell - for example, the rocker/rstudio container works just fine with port 8787. When I run the shiny container I do not get any feedback in the console, it pauses for a bit and then gets me the prompt back - then I check running containers and nothing is running.

**Comment by cboettig** [comment]
@hahnemann That does indeed sound like a hardware issue; I'm just guessing the container is crashing due to unavailable memory requirements or some such issue; those issues can be pretty opaque with so many layers of virtualization.  Can't reproduce on our end and not sure there's anything we can do it, I think you'd have more luck pursuing in a general docker forum. Any reason you can't use the native Docker for Mac? https://docs.docker.com/docker-for-mac/install/ . Apparently it works with El Capitan, and that would remove a few of your virtual layers.

**Comment by hahnemann** [comment]
I understand. The setup I'm using doesn't make sense as I am only testing possibilities; this works well with the same setup by replacing Alpine with RHEL. I appreciate the time in testing and looking at this. Terrific containers BTW!
