### ISSUE TITLE
Volume permission issue

### ISSUE THREAD

**Issue by keqiang** [rocker-org/shiny#27]
I'm currently using this Docker image to deploy Shiny Apps. I ran into an issue where I needed to mount a volume from the host machine to the Docker container. Since the Shiny server in the container runs each Shiny app using the user 'shiny', who has no access to these mounted volumes. I checked the rstudio docker repo about how to start docker using a different user(Uid), but even if I start the docker container using user 'shiny', it doesn't help.

I'm mounting the volumes because these files are rather large and users want to use Shiny app without uploading them, or even just some large files shared by all users(don't want to put the files in the docker container).

Currently, I just want to be able to read the files. It seems writing files to the host volumes would be more difficult.

Thanks!

**Comment by cboettig** [comment]
>  even if I start the docker container using user 'shiny', it doesn't help.

Docker doesn't care what the user name is, you need to make sure the UID in the container matches the UID of the host user.  Do check out the wiki:

https://github.com/rocker-org/rocker/wiki/Sharing-files-with-host-machine


e.g. if you do `docker run --rm -ti -u shiny rocker/shiny id` you'll see this creates a user named `shiny` with UID 999.  If your host system has the usual default single user, it's probably userid 1000, so these don't match.  What you want to do is pass your UID number (e.g. 1000), not your user name:

if you run `docker run --rm -ti -u $UID rocker/shiny id` and you should get a user on the container with matching UID.  

hope this helps,

Carl

**Comment by keqiang** [comment]
Thanks for your reply Carl!

I tried using the command you suggested by 'docker run -p 3838:3838 -d --name test -u $UID rocker/shiny' but the container won't start. When I get rid of the -d switch, it prompts the following:

> chown: changing ownership of '/var/log/shiny-server': Operation not permitted
[2017-07-27 17:26:17.365] [INFO] shiny-server - Shiny Server v1.5.4.858 (Node.js v6.10.3)
[2017-07-27 17:26:17.371] [INFO] shiny-server - Using config file "/etc/shiny-server/shiny-server.conf"
[2017-07-27 17:26:17.429] [ERROR] shiny-server - Error loading config: The user 'undefined' does not have permissions to run applications as one of the users in 'shiny'. Please restart shiny-server as one of the users in  'shiny'. (/etc/shiny-server/shiny-server.conf:2:1)
[2017-07-27 17:26:17.430] [INFO] shiny-server - Shutting down worker processes

It seems the UID we specified is not in the 'shiny' group.

**Comment by cboettig** [comment]
That's a good point, maybe @wch can weigh in.  I don't see an easy way around this; basically you have to run the container as root so you can add the user `docker` to the group `shiny` first and then switch to the non-root user and run the container:

```
docker run -p 3838:3838 -d rocker/shiny bash -e "adduser docker shiny && su docker && shiny-server.sh"
```

Clearly that's a bit ugly.  (also assumes your $UID is 1000, which is the UID of `docker` user which is already created on the system.  Otherwise you have to add even more to the command to create a new linux user with the right permissions).

**Comment by keqiang** [comment]
Looks like rocker/shiny container will always create a user named shiny, whose uid is 999. I guess it is done by installing Shiny server. I don't know if this can be parameterized by using a Docker run variable to specify with which UID should the Shiny Server run apps, basically using the command parameter -u to substitute for the default 'shiny' user that to be created.

**Comment by antortjim** [comment]
I just added the shiny user to the docker group and made the shiny-server script the ENTRYPOINT
`RUN adduser shiny docker`
`ENTRYPOINT shiny-server.sh`

 mount passing the --mount parameter to docker run using the Docker image produce by the built using the above Dockerfile. My app files are loaded into the container with the -v flag
`docker run  -dP \`
`--mount source=/host_data,target=/home/data \` 
`-v /path/to/shinyapp:/srv/shiny-server/`

This enables sharing of files between /home/data in the container and the /host_data dir in the host, while giving the shiny app permission to modify the files because the user running it, **shiny**, is now included in the **docker** group. I didn't need to modify any other permissions or specify a UID.
