### ISSUE TITLE
Stuck with package '<package name>' was installed by an R version with different internals...

### ISSUE THREAD

**Issue by Emelieh21** [rocker-org/shiny#48]
Hey, I know this issue was already brought up and closed, but I am really stuck here. We were using an shiny server based on rocker/shiny + some extra stuff/packages. Since yesterday I tried to rebuild the whole image, but I keep getting these errors in the building process and all my apps crash because the packages are missing:

`Error : package ‘<package name>’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version`

My docker file starts like this:
```
FROM rocker/shiny

RUN rm /srv/shiny-server/index.html && \
	rm -rf /srv/shiny-server/sample-apps && \
	apt-get update && \	
	apt-get install -y python python-pip && \
        pip install awscli && \
	apt-get install -y libudunits2-dev && \
	apt-get install -y r-cran-rjava && \
	apt-get install -y libcurl4-openssl-dev && \
	apt-get install -y libssl-dev && \
	apt-get install -y libgdal-dev && \
	apt-get install -y libxml2-dev && \
	apt-get install -y libjq-dev && \
	R -e "install.packages('devtools', repos = 'http://cran.rstudio.com/')" && \
	R -e "devtools::install_github('cloudyr/aws.ec2metadata')" && \
	R -e "devtools::install_github('cloudyr/aws.signature')" && \ 
        ....
```
Everything used to work fine before. Am I doing something wrong? Did anything change?

**Comment by eddelbuettel** [comment]
You are mixing R 3.4.* and R 3.5.*. You need to be more careful about which repositories, and R versions, you are accessing.   That is an error that is likely entirely entirely on your side.

**Comment by Emelieh21** [comment]
Thanks @eddelbuettel for the fast response! Maybe a stupid question, but how do you know I am mixing R3.4.* and R3.5.*? I didn't realize it, I am just using the same docker file as before.

**Comment by eddelbuettel** [comment]
Launch your container with `bash` and at the prompt do `apt-cache policy r-base-core`. You'll see where it comes from.  Do the same with any package that goes belly up: `apt-cache cache policy r-cran-curl` (to name one).

There is no Docker bug here.  You have an issue in your add-on work, so I will gently close this.  If you find a reproducible issue from our side by all means please reopen and document.

**Comment by cboettig** [comment]
@Emelieh21 Sorry, this is my fault.  I've transitioned the `shiny` image to build on `debian:stable` rather than `debian:testing` (to align with RStudio and provide the versioned images that were requested).  So indeed they are not the same images as ~ 1 month ago (see PR #24)

This approach does not play nicely with `apt-get r-cran-*` because in the versioned stack, R is installed from source.  I recommend installing R packages directly from CRAN (e.g. the `r-cran-rjava`) or otherwise you'll pull in a copy of the older R that ships in `debian:stable` (at `/usr/bin/R`) in addition the the already installed latest R (at `/usr/local/bin/R`), which you probably don't want.

**Comment by eddelbuettel** [comment]
@cboettig Can you detail what you mean by `r-cran-rjava`?  That is (again) a binary build and as such susceptible to mixing R 3.4.* and R 3.5.*.  If you have backports in mind, point to the relevant URL and `apt add-repo` lines.   Else say you meant `install.packages("rJava")` with all its dependency issues.

Maybe use Ubuntu LTS instead?   We'd get the Rutter repo there....    Or stick with testing instead?

**Comment by cboettig** [comment]
@eddelbuettel Right, @Emelieh21 's Dockerfile includes `r-cran-rjava` in the apt-get line above.  It he changed it to `install.packages("rJava")` like you say (and handled the dependency issues, e.g. `default-jdk`) then I think the above problem mixing versions would go away.  

I don't see how Ubuntu LTS would help.I'm not sure how to take a vanilla Debian or Ubuntu image, install the desired version of *R from source only*, and still have things so that users can `apt-get install` R binaries from anywhere.  Any `r-cran-` binary is going to depend on the binary build of R and so it's going to install a second version of R into `/usr/bin` in addition to the one I installed manually from source at `/usr/local/bin`, right?

**Comment by eddelbuettel** [comment]
You can definitely mix-and-match 'R from source' with `r-cran-*` provided you use the same R version (or "newer than").  That is what everybody does who builds R from svn or git anyway -- it happily uses packages from anywhere in `.libPaths()` provided they come from a compatible version.  There are times when you could -- a year ago when what is now r-release was r-devel and was imposing a change to the then r-release.  Right now we don't.    And obviousy if you rebuild _the same r-release from source_ you get the same r-release and they match.

Devil, as always, in the detail.  Happy to take off-line and poke at particular Dockerfiles.

**Comment by Emelieh21** [comment]
@cboettig Thanks a lot for clarifying! Looking a bit deeper I see the stable r-cran-rjava came with R 3.2.3... I took `apt-get install r-cran-rjava` out now and replaced it with:

```
apt-get install -y default-jdk && \
apt-get install -y libicu-dev && \
apt-get install -y libbz2-dev && \
apt-get install liblzma-dev && \
R -e "install.packages('rJava')"  &&\
```
Stuff seems to look normal again :) Thanks again for the quick reactions from your side.

**Comment by eddelbuettel** [comment]
(You can combine those calls as

```
apt-get install -y default-jdk ibicu-dev libbz2-dev liblzma-dev && \
     R -e "install.packages('rJava')"  &&\
```

and of course line-break the packages ... )

**Comment by Emelieh21** [comment]
That does looks much nicer. Thanks for the tip :)

**Comment by HarshGrandeur** [comment]
You must have upgraded to a newer version of R, but R did not automatically update packages. You first need to find packages with older version and update them.
Find the
`new_packages <- installed.packages()`
this will store all the package installed inside a data frame
convert into a dataframe
`df <- as.data.frame(new_packages)`
find older package versions , replace the list with packages which are of latest version and you dont want to update
`D2 = subset(df, !(Built %in% c('4.0.0','4.0.2')))`
`D2 <- as.data.frame(D2)`
Finally install the packages :
`install.packages(D2$Package)`
